"""esquema inicial — las 6 tablas del Módulo 1 (motor contable)

Revision ID: 0001_esquema_inicial
Revises:
Create Date: 2026-09-08

Tablas: cuenta, asiento, linea_asiento, tercero, factura, contrato.
Ver docs/features/contabilidad-nucleo/spec.md §4 y docs/arquitectura/base-de-datos.md.
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001_esquema_inicial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('origen', sa.Enum('FACTURA', 'CONTRATO', 'MANUAL', name='origenasiento'), nullable=False),
    sa.Column('libro', sa.Enum('OFICIAL', 'INTERNA', name='librocontable'), nullable=False),
    sa.Column('documento_soporte', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('ACTIVO', 'PASIVO', 'PATRIMONIO', 'INGRESO', 'GASTO', name='tipocuenta'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cuenta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cuenta_codigo'), ['codigo'], unique=True)

    op.create_table('tercero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('nit_cedula', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.Enum('CLIENTE', 'PROVEEDOR', name='tipotercero'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tercero_id', sa.Integer(), nullable=False),
    sa.Column('objeto', sa.Text(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('VIGENTE', 'TERMINADO', name='estadocontrato'), nullable=False),
    sa.Column('archivo_original', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tercero_id'], ['tercero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contrato_tercero_id'), ['tercero_id'], unique=False)

    op.create_table('factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('EMITIDA', 'RECIBIDA', name='tipofactura'), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tercero_id', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PAGADA', 'ANULADA', name='estadofactura'), nullable=False),
    sa.Column('asiento_id', sa.Integer(), nullable=True),
    sa.Column('archivo_original', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['asiento_id'], ['asiento.id'], ),
    sa.ForeignKeyConstraint(['tercero_id'], ['tercero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('factura', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_factura_tercero_id'), ['tercero_id'], unique=False)

    op.create_table('linea_asiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asiento_id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('debito', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credito', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['asiento_id'], ['asiento.id'], ),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuenta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('linea_asiento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_linea_asiento_asiento_id'), ['asiento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_linea_asiento_cuenta_id'), ['cuenta_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('linea_asiento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_linea_asiento_cuenta_id'))
        batch_op.drop_index(batch_op.f('ix_linea_asiento_asiento_id'))

    op.drop_table('linea_asiento')
    with op.batch_alter_table('factura', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factura_tercero_id'))

    op.drop_table('factura')
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contrato_tercero_id'))

    op.drop_table('contrato')
    op.drop_table('tercero')
    with op.batch_alter_table('cuenta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cuenta_codigo'))

    op.drop_table('cuenta')
    op.drop_table('asiento')
    # ### end Alembic commands ###
