"""enlaces a documentos — enlace_rut en tercero; archivo_original -> enlace_documento

Revision ID: 0002_enlaces_documentos
Revises: 0001_esquema_inicial
Create Date: 2026-09-09

`archivo_original` (nunca usado) se renombra a `enlace_documento` y sube a 500
chars. Ver docs/features/documentos/spec.md.
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0002_enlaces_documentos"
down_revision: str | None = "0001_esquema_inicial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enlace_documento', sa.String(length=500), nullable=True))
        batch_op.drop_column('archivo_original')

    with op.batch_alter_table('factura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enlace_documento', sa.String(length=500), nullable=True))
        batch_op.drop_column('archivo_original')

    with op.batch_alter_table('tercero', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enlace_rut', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tercero', schema=None) as batch_op:
        batch_op.drop_column('enlace_rut')

    with op.batch_alter_table('factura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo_original', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('enlace_documento')

    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo_original', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('enlace_documento')

    # ### end Alembic commands ###
